name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master, development ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Install Node.js dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Run backend tests
      run: |
        cd backend
        python -m unittest discover tests

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false
      
  lint:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Python linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy
        
    - name: Install Node.js linting tools
      working-directory: ./frontend
      run: npm install eslint --save-dev
      
    - name: Run Python linting
      run: |
        flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
        mypy backend
        
    - name: Run JavaScript linting
      working-directory: ./frontend
      run: npx eslint src

  build:
    runs-on: windows-latest
    needs: [test, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build backend
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          frontend/build
          backend/**/*.py
